#include <iostream>
using namespace std;
int main() {
	cout << "                  ^7YPB##&&&&&&&&&##BGGGGGPPYYYPPPPPPGGGGGBBBB#BB###BGPY7^:.                    "   << endl;
	cout << "               ^75B##&&&&&#&&&&##BGBBBBBGP555555YJYY5Y5PPGBBB###########GY!^^:.                 "   << endl;
	cout << "            :!5B#&&&&&####&&#BGGGBBBBBBBGGBGGGGP55YYYY5PGBB#BBBBB######&&&BJ~:::.               "   << endl;
	cout << "          ^JG#&&&&&####&&&#BBBBBBB####BBBGGGGGGP5YYY5PPPGGGGBBBB#######&&&&&#57^::              "   << endl;
	cout << "        ~YB&&&&&&###&&&&#BB#######BBBGGGBBBBBGGP5YJJ55555PPGGGBB####B##&&&&&&&#P7^.             "   << endl;
	cout << "     .!5B##&&&&&#&&&&&#####&###BBBBBBB######BBBGGGGGP555555PGBBBB###B####&&&&##&#57^            "   << endl;
	cout << "    ^JPB&&&&&&&&&&&&&#&&&&####B####&&&&&&#####BBBBGPP55555PBBBGBBBBBBBB###&&&&&&&&#G?.          "   << endl;
	cout << "    :?B&&#&&&&&&&@&#&&&&####&&&&###########BBBBBBBBBGGGGPGGPPPGGGGPPPPGBB####&&&&&&&#P~         "   << endl;
	cout << "    7B&&&&&&&&&&@&&&&&&&&&&&&########BBBBGGGGBBBBBGGGGPP55PPP5PP5YYYYYJYPGB##&&&&&&&##BJ.       "   << endl;
	cout << "   ~#&##&&@&&&&@&&&&&&&&&&##BBBBBBGGGGGGBB#####BBBGGBGGPP555555YJJJ?J777J5GB##&##&&&&##BY:      "   << endl;
	cout << "   J&&&&&@&&&&&&&&&&&&&######B#BB#######&&###BB#BBBBGGGGPPPP5YJ????77!7!!7YPG##&&&&&&&#BGJ.     "   << endl;
	cout << "  ^B&&@&&&&#&&&&&########&&##############BB#BBBBGGBBBBBBGGPYJ?7?77777!!!!~!JGB##&&&&&&#BGP?     "   << endl;
	cout << "  J&@@@@@&&&&&&&&###&&&&&&&&############BBBGGGBB###BBBBGP5YJJ???777!!~~~~~~!JG##&&&&&&&BPPP^    "   << endl;
	cout << " !#@@@@@@@&&@@@&##&&##&&&&##########BBBGGGBB######BGGGPP55YJJ??7!~~~~~~~~~~~!5B#&&&&&&#G555?    "   << endl;
	cout << "^B@@@@@@@@@@@@&&&&&&############BBBBB#######BBBBBGPPP55YJJJ?!!~~~~~~~~~~~~~~~?G###&&&&BP555J:   "   << endl;
	cout << "G@@@@@@@@@@@@&&&&&&######################BGGGGPPP55YJ?77!!~~~~~~~~~~~~~~~~~~~7PB###&&#GPPGJ7^   "   << endl;
	cout << "@@@@@@&@@@@@@@@@&&&#################BBBGGGPP55YYJJ?77!!~~~~~~~~~~~~~~~~~~~~~~7PB###&##BG5BJ!^   "   << endl;
	cout << "@@@@@&@@@@@@@@@@&&########BBBBBBBBBBGGPPGGPPYJJ?77!!!~~~~~~~~~~~~~~~~~~~~~~~!?GB###&#BBPGP?~^   "   << endl;
	cout << "&@@@&&@@@&@@@@@@&&&&#########BBBBBBBBB##B##BGPYJ77!!!!!~~~~~~~~~~~~~~~~~~~~!!JGGBBB###BPGJ7~:   "   << endl;
	cout << "&&@&&&&@&@@@@@&&&&##&&&#B#####################BGP5J?7!!!!~~~~~~~~~~~~~~~~~~!!JGGBB####PPP?7~.   "   << endl;
	cout << "@&&&&&&@@@@@@@&###&&&#PB########################BBPYJ?7!!!!!~~~~~~~~~~~~~~~~!?PGBB###BPPY?!:    "   << endl;
	cout << "&&&&&&@@@@@@@&&&###BBGYBBGGGBB#####BBGGBB###B###BBBPYJ?7!!!!!!!!!!~~~~~~~~~~~!5GBB#BBGP5Y?~     "   << endl;
	cout << "&&&&&&&&&&&&&&&###GPP5J5YJYY5GBBBBB##&##BBBBBBB##BBG5YJ?77!!!7!!77777!!!~~~~~~7PBBBBGP55J?:     "   << endl;
	cout << "#&&&&&&&&&&&&&###BGGGY555YYJYY5PPP55Y5PP5B###GGBBBPGPYJ?77!!!77??JY555555YJ?777YB#BBPPP5J!      "   << endl;
	cout << "#&#&&&&&&&&&&####BBBBYPP5YYJJJJJYYYYYJJ??JYPGBBBBBBBBPJ7!!!!!7JJYPPGGGGGGGGPP5YYB#BGPPPY7.      "   << endl;
	cout << "##&&&&&&&&&&&####BGPG?5P55YJJJJ?????????JJJ?JYPB#B#BGP5Y??7~7J5PGBBBGGGPP55YYYYYBBGPPP5?.       "   << endl;
	cout << "&##&&&&@&&&&#####BGPGYY555YJJJ????77777????J5BBB##BPY?7!!7J?5YYPGGP5YJJ?YP55Y?7JGGGGG5J.        "   << endl;
	cout << "&&&&&&&&&&&#########BBGP5YYJJJ??7777777777JPB#B#BGP5J?!!~~!757YPBB##BPY??5P5555PGPGBG5:         "   << endl;
	cout << "&@@@&&&&&&###########BBBGGPP5YJ??77!!!!!!!J5PBBGP555Y7!!~!7JPYJJY5PPPJYP5YYJYPP5PGGG5^          "   << endl;
	cout << "&@@@@&&&&##########BGP55YJJJJJYYYYJJ????77?5BGP5PPP5J7!!!!75#BY??JJJ?JJJ??7YBBGPPG55~           "   << endl;
	cout << "&&&@@@&&&#########BBGP5YJ?77!!!!!!77?JYY55PPPGGGGP5Y?7!!!!7YP?!!!!7777777!7PGGP5GGY~            "   << endl;
	cout << "&&&&@@&&###########BBGPYJ??777!!!!!!777?YPPPGBBBBG5J?7!!!!!J5!!!!!!!!!!!!7?PPPPPG5~             "   << endl;
	cout << "&&&&@@@&############BGP5YJ??777777777J5GBGGPPPGGGP5J7!!!!!!?P7!~~!!!!!!!!!?PGPGPJ^              "   << endl;
	cout << "&&&&&@@&############BGP5YJJ??777!!!7YGB#BBBBBBBBGPY?7!!~~!!7JY?77!!!!~~~!7PGGG5!.               "   << endl;
	cout << "&&&&&&@&############BGPYYJ??7777777YGBB##########BGY?7!!!!!777777?????????YJ7~.                 "   << endl;
	cout << "&&&&&&&&###########BGGPYJJ??77?????YGBB####&######BPY?7??7!!77!!~~~~~!!7!!~                     "   << endl;
	cout << "&&&&&@@&&&#########BGGPYJ??7?Y555YJ?JJ5GB#######BGP5YJJJ7!~!!777!~~~~~~~~~.                     "   << endl;
	cout << "GGBBB##&###&#######BBG5JJ?7!?B#BBGP5YJ??JJYYYYY5Y?7!!!!~~~~~!!77!!!~~~~~^.                      "   << endl;
	cout << "GGGGPPPPGGGGBB#####BBG5JJ?!!?G#&####BGP55YJ7!!!77!!!~~~!~~~~~~!7!!!!~!~:                        "   << endl;
	cout << "GPPPPPPPPP55PPPGBB##BGYJJ?7!7?Y5GGBBBBBBGP55Y?7!!!!!!~!!~!!!!!~!7!!!!^                          "   << endl;
	cout << "PPPP5P555555555555PGGG5JJJ?77?YY555555YY55PPP5YYJJJ???77!!777!!!777~.                           "   << endl;
	cout << "PPP555555555555555YYY55YYJJ??JY5PP555YY?77?????JJJ?JJJYJJ?7?7!!!7!:                             "   << endl;
	cout << "GGP55555555555555Y5YYYYYYYYJ?JJY555YYYYYJJ?????7777?777!!!!7!!!!^                               "   << endl;
	cout << "PGG55555P5PP5YYYYYY5YYYYYYYY??JJJYYYJJ?JJJJ??????777!!~~~!!!7!~.                                "   << endl;
	cout << "PGGPPP55P55P55555555YYYYYYY5J7???????77???????777!!!!!!!!!77~.                                  "   << endl;
	cout << "PBGGPP55PP5555555YYY5YYYYYY55?7777!!!!!!!!!7777!!!!!!!!!!7~:                                    "   << endl;
	cout << "PPGGPP55PP555P55555555YYYY555Y7!!!!!!!!!!~~~~~!~!!!!!!!!~.                                      "   << endl;
	cout << "GP5PPPP555555555555555555YYYY5J7777!!!!~~~~~~~~~~~~!!!~.                                        "   << endl;
	cout << "GG55PPPPP55555555555555555YYY55??77!!!!!!~~~~~~~~~!!^.                                          "   << endl;
	cout << "GG55PPPPPP55555PPPP555555555YY55Y??77!!!!!!!!!~!!!^.    										"		 << endl;
	return 0;
}